### ISSUE TITLE
ints being interpreted as floats

### ISSUE THREAD

**Issue by akbinod** [RandomFractals/vscode-data-preview#328] opened 2023-03-11 13:21 UTC
Thank you for this extension - it is helping a lot :)

My .tab file only contains ints. Some columns are correctly displayed as int, but others are represented as floats with no discernible pattern. I've attached a file with tab separated values - renamed it to .txt since .tab cannot be uploaded.

TIA.
[sample.txt](https://github.com/RandomFractals/vscode-data-preview/files/10948605/sample.txt)

**Comment by RandomFractals** [comment] 2023-03-13 12:05
@akbinod try our Tabular data viewer and see if you get better results. Just change the default `view` setrting to `Perspective`. See: https://github.com/RandomFractals/tabular-data-viewer#settings

Tabular data viewer uses more recent version of Perspective viewer for data display.

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.tabular-data-viewer

**Comment by RandomFractals** [comment] 2023-03-13 12:15
Actually, this is the grid view I get in tabular data viewer.

Columns that have 0 on the first row are interpreted as floats by default.

![image](https://user-images.githubusercontent.com/656833/224698515-f5cb0417-d9d5-459c-bb1d-15fb84ea848d.png)

Please include screenshots next time. I will close this ticket as duplicate of #321. There are a few other closed tickets with similar issue due to perspective viewer evaluating data type based on the first row column values.

**Closed by RandomFractals** 2023-03-13 12:15 UTC
Labels: duplicate

**Comment by RandomFractals** [comment] 2023-03-13 13:26
good news: you can change this in the new Tabular data viewer extension. See how for your sample data below:

![tabular-data-viewer-floats-precision](https://user-images.githubusercontent.com/656833/224715230-55ce2b41-e7d7-4c44-968d-48e529bb4932.gif)

**Comment by akbinod** [comment] 2023-03-24 09:16
Hi Taras

Thank you for your email. Unfortunately, the extension you mentioned is no longer available on the VS Marketplace.

Regards

BInod
