### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by alphainfinitus** [RandomFractals/vscode-data-preview#237] opened 2020-11-15 09:49 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.2.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ALPHAI~1\AppData\Local\Temp\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment] 2020-11-15 13:08
duplicate of #173

**Closed by RandomFractals** 2020-11-15 13:08 UTC
Labels: duplicate
