### ISSUE TITLE
Unable to preview data on mac

### ISSUE THREAD

**Issue by universalmind303** [RandomFractals/vscode-data-preview#162] opened 2019-11-18 14:12 UTC
VSCode version:  
1.40.0 x64

OS version:
Mac OS
Mojave 10.14

Errors: 
`[Embedded Page] data.view:refresh(): error: viewer.load is not a function`
`[Embedded Page] Uncaught TypeError: viewer.restore is not a function`

**Comment by RandomFractals** [comment] 2019-11-18 15:08
that's new. I don't have a mac, but I can check it on my win machines.

might be related to the viewer js libs update. I'll look into it.

is this only for data preview restore on vscode reload? || does it happen every time you try to data preview with that vscode v1.40 setup?

& thanks for reporting this!

**Comment by RandomFractals** [comment] 2019-11-18 16:08
@universalmind303 

|| did you just install || updated my extension without vscode reload? I belive vscode prompts you for that.

anyhoo, those errors are related to perspectiveJS viewer. 

Can you please clip the whole Data View Console stack for me to help you troubleshoot this?

**Comment by RandomFractals** [comment] 2019-11-18 19:07
closing this as another can't reproduce/invalid issue since my remote mac devs reporting all is kosher in that field ;)

![data-preview-on-mac](https://user-images.githubusercontent.com/656833/69081769-50cd4c00-0a04-11ea-985f-f624be1e42fb.jpg)

**Closed by RandomFractals** 2019-11-18 19:07 UTC
Labels: invalid, wontfix
