### ISSUE TITLE
Stuck at 'Loading data...'

### ISSUE THREAD

**Issue by uunal** [RandomFractals/vscode-data-preview#249] opened 2021-02-08 14:39 UTC
![stuck-at-loading](https://user-images.githubusercontent.com/2520197/107233542-c1aaba80-6a33-11eb-9abb-0d4fe8203c08.png)

After VScode update(I guess), extension stops  at 'Loading Data...' and this is the console output.

Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Thanks for help.

**Comment by RandomFractals** [comment] 2021-02-08 16:07
@uunal looks like you are trying to load a large csv with over half a million records.

Based on your trace data preview should be displaying it after some time since it read the file and shows records count.

Also, I can't troubleshoot masked local data files.

Please try it with one of the files from this repo data folder.

If you don't mind, I am going to close this issue as not reproducible since I just tried it with a few different files and don't see any changes in that vscode v1.53.0 that would change the behavior of this extension.

**Closed by RandomFractals** 2021-02-08 16:07 UTC
Labels: invalid, wontfix

**Comment by uunal** [comment] 2021-02-09 08:50
Thanks for the quick response.

As you suggested, I've tried with StateCapitals.csv and chicago-homicides-2001-2018(as large data file example). Results are the same as before. StateCapitals.csv has 50 records  and it stucks at loading data.

What kind of information should I give you to reproduce the results?

**Comment by kynac1** [comment] 2021-02-10 01:30
I can replicate this. I've tried with a variety of csv and json files and they all get stuck at loading data. It's not related to size; a test case I used was:
```
a,b
1,2
```

The running extensions window showed 2 uncaught errors for data preview, and gave this info. I assume it's related to this issue:

- Issue Type: `Bug`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.2.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 787,
		"activateCallTime": 1,
		"activateResolvedTime": 53,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "RandomFractalsInc.vscode-data-preview",
				"_lower": "randomfractalsinc.vscode-data-preview"
			},
			"activationEvent": "onLanguage:csv"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'length' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'length' of undefined"
		}
	]
}
```
Hope that helps track down the problem.!

**Comment by programmiererei** [comment] 2021-02-25 19:26
Duplicate to  #250 and #252
