### ISSUE TITLE
Extension causes high CPU load

### ISSUE THREAD

**Issue by Ch1kku64** [RandomFractals/vscode-data-preview#215] opened 2020-08-04 07:49 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\niksh\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt
[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/5020837/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment] 2020-08-04 11:12
duplicate of #173

**Closed by RandomFractals** 2020-08-04 11:12 UTC
Labels: duplicate, wontfix
