### ISSUE TITLE
avro preview intermittently succeeds

### ISSUE THREAD

**Issue by drdamour** [RandomFractals/vscode-data-preview#317] opened 2022-11-08 15:55 UTC
on vscode 1.73.0  and extension version

have an avro file, i would say 9/10 times i try to preview avro file i get the following error in debug console

![image](https://user-images.githubusercontent.com/1514496/200612486-df5ed0b7-1bab-4674-857f-56d26724f034.png)

but once in a while, it succeeds, awesome when it does...

tried a few different files, but they're all sourced from outputs of azure stream analytics jobs here's one just remove the .log (had to name it as such to let me upload to GH)

[716329542_fa25188d60cf440085d4a902f5bb6e77_1.avro.log](https://github.com/RandomFractals/vscode-data-preview/files/9962918/716329542_fa25188d60cf440085d4a902f5bb6e77_1.avro.log)

**Comment by RandomFractals** [comment] 2022-11-08 21:40
quit possible. try switching to light data preview theme as suggested in the pinned issue.

**Comment by drdamour** [comment] 2022-11-09 19:49
yes it seems related to #250 light seems to work a bit better, suggest renmaing that issue to be like CSV and others liek avro maybe?

**Comment by RandomFractals** [comment] 2022-12-22 10:27
Closing as duplicate of #250

**Closed by RandomFractals** 2022-12-22 10:27 UTC

**Comment by drdamour** [comment] 2022-12-22 17:05
@RandomFractals i get the behaviour in light mode too just less often.  i don't think it's specific to dark mode
