### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ChayanitBhateja** [RandomFractals/vscode-data-preview#271] opened 2021-04-27 09:47 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Linux x64 5.4.0-72-generic`
- VS Code version: `1.55.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 27313,
		"activateCallTime": 25,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "RandomFractalsInc.vscode-data-preview",
				"_lower": "randomfractalsinc.vscode-data-preview"
			},
			"activationEvent": "onLanguage:json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by RandomFractals** [comment] 2021-04-27 11:04
duplicate of #173

**Closed by RandomFractals** 2021-04-27 11:04 UTC
Labels: duplicate
