### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by neifors** [RandomFractals/vscode-data-preview#257] opened 2021-03-15 10:07 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 10137,
		"activateCallTime": 14,
		"activateResolvedTime": 25,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "RandomFractalsInc.vscode-data-preview",
				"_lower": "randomfractalsinc.vscode-data-preview"
			},
			"activationEvent": "onLanguage:json"
		}
	},
	"runtimeErrors": []
}
```

**Comment by RandomFractals** [comment] 2021-03-15 14:05
most likely duplicate of #173

**Closed by RandomFractals** 2021-03-15 14:05 UTC
Labels: duplicate, wontfix
