### ISSUE TITLE
Open formats error

### ISSUE THREAD

**Issue by christian102294** [RandomFractals/vscode-data-preview#274] opened 2021-05-08 16:38 UTC
Hello Data Preview team 

I'm trying to preview some formats (parquet, csv, json) but it doesn't work property, I'm using last version (currently 2.3.0) on MacOS Bigsur 11.3.1

CSV Example:
[salarios.csv](https://github.com/RandomFractals/vscode-data-preview/files/6446175/salarios.csv)
Error:
![image](https://user-images.githubusercontent.com/45155827/117546557-9adb3080-aff0-11eb-93bf-2f63a4bf95cc.png)

[Parquet Example from official documentation](https://github.com/RandomFractals/vscode-data-preview/blob/master/data/parquet/large.parquet)
Error:
![image](https://user-images.githubusercontent.com/45155827/117546749-9a8f6500-aff1-11eb-95a7-25e2c09d09c6.png)

**Comment by RandomFractals** [comment] 2021-05-09 19:18
duplicate of #250. see potential solutions there.

**Closed by RandomFractals** 2021-05-09 19:18 UTC
Labels: duplicate
