### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Flykun** [RandomFractals/vscode-data-preview#189] opened 2020-02-28 09:32 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\16898\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment] 2020-02-28 12:28
duplicate of #173

**Closed by RandomFractals** 2020-02-28 12:28 UTC
Labels: duplicate, wontfix
