### ISSUE TITLE
can't to open files on Windows 10 (TBD)

### ISSUE THREAD

**Issue by S-Maciejewski** [RandomFractals/vscode-data-preview#141] opened 2019-09-04 11:09 UTC
The extension is really useful, however I encountered a bug similar to the one mentioned in issue #124 - the extension doesn't see the file I'm trying to open, except this issue is occuring on Windows 10 (version 1903). It used to work previously (a few versions back, 1.3x.0), but I can't fix it since. Tried reinstalling the extension and VS Code itself, nothing helped. Would appreciate help with this one, becouse as I said, extension proves to be really useful :) 
![image](https://user-images.githubusercontent.com/20989002/64249966-37dcf080-cf15-11e9-9eed-ede43e47761d.png)

**Comment by RandomFractals** [comment] 2019-09-04 11:15
agh! I must have broke it again in my last refactor. sorry about that.

I'll add some tests and will try it on win10 today.

Looks like you are using vscode v1.37?

Thanks for letting me know.

**Comment by S-Maciejewski** [comment] 2019-09-04 11:21
I'm using  VS Code v1.37.1, thanks!

**Comment by RandomFractals** [comment] 2019-09-05 15:24
@S-Maciejewski btw, I am hoping to get to this soon, but have you tried vscode v1.38?

There were quite a few things broken in that v1.37.1 release related to webviews restore and fs/uri api changes.

Can you see if this was patched up in that vscode v1.38 released yesterday too?

https://twitter.com/code/status/1169310819894476803

**Comment by sbgillett** [comment] 2019-09-05 16:31
Same issue in 1.38 here I'm afraid

**Comment by RandomFractals** [comment] 2019-09-05 16:52
@sbgillett ok will try to patch it soon. thx for checking

**Comment by RandomFractals** [comment] 2019-09-07 15:51
@S-Maciejewski & @sbgillett: quick follow up q. on this:

how are you trying to launch data.preview on your win10s? there are like half a dozen of ways to do it:

https://github.com/RandomFractals/vscode-data-preview#data-preview--launch-tips

are you saying none of them work for you?

I could use more info on that to close this. thanks!

**Comment by twsI** [comment] 2019-09-09 09:20
Same here, neigher starting the data preview via command palette nor using the dedicated icon seems to work. Using the version 1.38.0. Anything else you need? If I can find, I'll try the debug build

**Comment by RandomFractals** [comment] 2019-09-09 09:31
@twsI yeah, try the ext. dev/debug build & run. you should get more msgs on paths for data files loading, if you have time.

I'll look into this too. I def. want it to work on win10. thanks!

**Comment by RandomFractals** [comment] 2019-09-10 10:59
@S-Maciejewski @sbgillett & @twsI hey guys, I just pushed new v1.41 that hopefully fixes this issue.

If not I'll have to dive deeper into vscode Uri implementation which is a bit wonky.

Let me know if this is resolved for your win10 builds & please don't forget to star & provide feedback in store: https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview&ssr=false#review-details

**Comment by RandomFractals** [comment] 2019-09-10 11:02
alternatively, I am considering switching to new vscode.worspace.fs api which provides support for remote data files too: https://github.com/microsoft/vscode/issues/78094

**Comment by sbgillett** [comment] 2019-09-10 11:14
Sorry but still not working for me following update to v1.41. Let me know if I can do anything to provide further details.

**Comment by RandomFractals** [comment] 2019-09-10 11:17
hah! ok. I think I'll be switching to new vscode.workspace.fs api then.

**Comment by RandomFractals** [comment] 2019-09-10 12:05
@sbgillett actually, can you try one of the data files from my sample/test folder: https://github.com/RandomFractals/vscode-data-preview/tree/master/data/json

I just had devs confirm that it works on mac & works on my win7 machine. I really don't see why this would be an issue on win10. 

Thanks!

**Comment by RandomFractals** [comment] 2019-09-10 12:35
I am closing this issues since I can't reproduce it. Please try a different data file.

<img width="1280" alt="vscode-data-preview-win10" src="https://user-images.githubusercontent.com/656833/64614157-1c4e6b80-d395-11e9-810c-1b17506b251b.PNG">

**Closed by RandomFractals** 2019-09-10 12:35 UTC

**Comment by twsI** [comment] 2019-09-10 13:39
Can confirm, that the latest version is now working for me on win10 too

**Comment by RandomFractals** [comment] 2019-09-10 15:04
p.s.: if you feel like this is a solid data ext for vscode, please start it here:

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview&ssr=false#review-details

I could use more stars in that degraded feedback ;) 

thanks for checking it out too & sticking with me through this recon.
