### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hrgh74** [RandomFractals/vscode-data-preview#307] opened 2022-08-12 03:00 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.1`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-loa
[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/9313393/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)
d

**Comment by RandomFractals** [comment] 2022-08-12 10:04
duplicate of #173

**Closed by RandomFractals** 2022-08-12 10:04 UTC
Labels: duplicate
