### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fajaede** [RandomFractals/vscode-data-preview#283] opened 2021-07-13 17:45 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.46.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/imac/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment] 2021-07-13 19:45
duplicate of #173

**Closed by RandomFractals** 2021-07-13 19:45 UTC
Labels: duplicate
