### ISSUE TITLE
Grid is empty

### ISSUE THREAD

**Issue by programmiererei** [RandomFractals/vscode-data-preview#252] opened 2021-02-25 13:49 UTC
VSCode 1.53.2; DataPreview 2.2.0; Windows 10 20H2 (german); 
fresh installation with standard configuration

Data:
Billing Month;Invoice Reference;Attached account;
2012;DE21010855;9165448884;DWP RE.NEOLINK FEES;
2012;DE21010855;9165448884;DWP RE.NEOLINK F;
2012;DE21013335;1030033584U;DWP RE HLB;
2012;DE21013335;9165444001;DWP RE HLB;
2012;DE21013335;9165448882;DWP RE HLB BILLI;

Result:
Data Preview is empty
but shows "Loading data..."

This happens with all csv (delimiter ",", ";" or tab)

But it worked three weeks ago.

**Comment by RandomFractals** [comment] 2021-02-25 17:28
sounds like a duplicate of #250. Something must have changed in the latest vscode version since there have not been any updates to this data preview extension for a few months.

**Closed by RandomFractals** 2021-02-25 17:28 UTC
Labels: duplicate
