### ISSUE TITLE
specify variable types when previewing files

### ISSUE THREAD

**Issue by gennaro-tedesco** [RandomFractals/vscode-data-preview#171] opened 2019-12-05 14:18 UTC
Would it be possible to force specify variable types through a configuration file or drop down menu next to the columns (or by hovering)? I have noticed that sometimes numerical formats are read as strings and viceversa, or maybe in some use cases one just needs to assert the types of such variables for easier sorting/filtering (based either on numerical conditions or string match).

Or is this already present and I have missed it?

**Comment by RandomFractals** [comment] 2019-12-05 16:11
This will be added in the next data preview release, with an option for you to change in the data preview config per dataset view.

I am just waiting for this perspective dates handling enhancement to be released: 

https://github.com/finos/perspective/pull/829

I am going to close this request as duplicate of #156 

I am aware of this shortcoming and looking to patch it soon!

**Closed by RandomFractals** 2019-12-05 16:11 UTC
Labels: duplicate

**Comment by RandomFractals** [comment] 2019-12-05 16:14
However, please keep in mind if your json data is a quoted string, it will be treated as a string, not a number.

See this json sample data file for how to adjust your number properties for now :) 

https://github.com/RandomFractals/vscode-data-preview/blob/master/data/json/cars.json

**Comment by gennaro-tedesco** [comment] 2019-12-06 08:44
I see, thank you for looking into it, I hope the new release is coming soon!

**Comment by RandomFractals** [comment] 2019-12-06 14:07
yeah, most likely next week. just sign up to watch releases
