### ISSUE TITLE
Specify column data type on csv, tsv import

### ISSUE THREAD

**Issue by murpheywa** [RandomFractals/vscode-data-preview#217] opened 2020-08-08 03:44 UTC
Sometimes import will type a column as numeric (123) when the data is a mix of numbers and strings.
When this happens, the non-numeric column values are converted to NaN.
I would like to be able to assign the column type myself. In this case, I would assign the column type as string.

**Comment by RandomFractals** [comment] 2020-09-28 03:11
duplicate of #156

**Closed by RandomFractals** 2020-09-28 03:11 UTC
Labels: duplicate
