### ISSUE TITLE
Date values converted to unix timestamps when exporting

### ISSUE THREAD

**Issue by mhkeller** [RandomFractals/vscode-data-preview#200] opened 2020-04-23 02:27 UTC
If I have a csv file of days in `YYYY-MM-DD` format, open it up in data-preview, and then save it out as a csv, the date field is a timestamp
<img width="221" alt="Screen Shot 2020-04-22 at 10 27 09 PM" src="https://user-images.githubusercontent.com/498744/80052338-71845b00-84e8-11ea-91a5-95c2ec67248d.png">

**Comment by RandomFractals** [comment] 2020-04-23 02:48
yeah, I need to add default date formatting for those.

**Comment by RandomFractals** [comment] 2020-04-23 02:49
duplicate of #156

**Comment by mhkeller** [comment] 2020-04-23 04:57
Sounds good! Feel free to close this if you prefer to track it on that issue or want to keep this up for whatever reason.

**Comment by mhkeller** [comment] 2020-04-23 04:58
Is there a way that it could preserve the input format?

**Comment by RandomFractals** [comment] 2020-04-23 05:30
like I said it's a duplicate of #156 that I did not finish.

see this commit for what needs to be added for csv save to format dates:

https://github.com/RandomFractals/vscode-data-preview/commit/bb7d56c1785b440612fdc55c28c2cede59b77f7f

**Closed** 2020-04-23 05:31 UTC
Labels: duplicate
