### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fajaede** [RandomFractals/vscode-data-preview#284] opened 2021-07-19 23:02 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Darwin x64 17.7.0`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/h1/lhk8fy6n7tl41k9ytlrmp2gm0000gq/T/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by fajaede** [comment] 2021-07-19 23:13
While i was testing AdminLTE i got this error.

**Comment by RandomFractals** [comment] 2021-07-20 12:10
duplicate of #173

**Closed by RandomFractals** 2021-07-20 12:10 UTC
Labels: duplicate
