### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by FANMixco** [RandomFractals/vscode-data-preview#205] opened 2020-06-14 10:24 UTC
[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/4776242/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\feder\RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RandomFractals** [comment] 2020-06-14 12:05
duplicate of #173

**Closed by RandomFractals** 2020-06-14 12:05 UTC
Labels: duplicate, wontfix
