### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by Rohansi** [RandomFractals/vscode-data-preview#285] opened 2021-07-20 23:42 UTC
I'm unable to open a very large (621MB) JSON Lines file. I get the following error:

> Unable to parse data file: 'performance-2021-07-20_19-09-43.jsonl'.         
>	 Line #: 1 Error: Cannot create a string longer than 0x1fffffe8 characters

Each line within the file is less than 500 characters so I assume it is trying to read the file into one massive string. Ideally it should be read line-by-line as  the format was intended to be read that way.

Unfortunately I cannot give this data out but it shouldn't be too hard to replicate.

**Comment by RandomFractals** [comment] 2021-07-21 07:52
duplicate of #167

**Closed by RandomFractals** 2021-07-21 07:52 UTC
Labels: duplicate
