### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Luune** [RandomFractals/vscode-data-preview#312] opened 2022-09-08 03:00 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 10763,
		"activateCallTime": 38,
		"activateResolvedTime": 87,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "RandomFractalsInc.vscode-data-preview",
				"_lower": "randomfractalsinc.vscode-data-preview"
			},
			"activationEvent": "onLanguage:json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by RandomFractals** [comment] 2022-09-08 10:43
Closing as duplicate of #173.

Yet another generic report of extension loading from vscode without any info about data being loaded, etc.

Also, note that data preview will be rebundled soon to speed up data preview loading. See ticket #311.

**Closed by RandomFractals** 2022-09-08 10:43 UTC
Labels: duplicate
