### ISSUE TITLE
Previews Broken on Linux

### ISSUE THREAD

**Issue by fny** [RandomFractals/vscode-data-preview#152] opened 2019-09-24 03:37 UTC
More pain perhaps related to #136, #141 I'm afraid. 🤔

Something's wonky on Linux still. I'm running VSC 1.38.1 and running the latest version of your extension: 1.47.0.

Here's what I see when loading a csv:

```
> document.readystatechange complete

 data.view:complete!

> loadDataInfo()

 data url: file:///home/DFD/fny/projects/management/dev/data/raw/visits.csv
 data table: 

> restoreConfig(
{})

> loadTableList(
 tableNames = []
 requestedDataTable = ''
)

> refresh(dataTable='')

 loading data: visits.csv ...

> getData()

 loading file data: visits.csv ...

> getData()

 records count: 195,822

> refresh(dataTable='')

 initializing data view: visits.csv ...

> 
```

**Comment by RandomFractals** [comment] 2019-09-24 11:23
@fny what's wonky? that data.view console log shows that it read your csv data & reported records count. do you not get a data grid displayed after that?

can you try some of the test data files from this repository from /data folder and send me data preview screenshot and what you see in dev tools console (any errors there?)

Thanks!

**Comment by RandomFractals** [comment] 2019-09-25 12:36
closing this as can't reproduce since that data.view log looks fine and no further info provided.

**Closed by RandomFractals** 2019-09-25 12:36 UTC
Labels: invalid
