### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by garagon** [RandomFractals/vscode-data-preview#282] opened 2021-07-10 03:02 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-data-preview`
- Extension Version: `2.3.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.0`

[RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt](https://github.com/RandomFractals/vscode-data-preview/files/6794574/RandomFractalsInc.vscode-data-preview-unresponsive.cpuprofile.txt)

**Comment by RandomFractals** [comment] 2021-07-10 12:16
duplicate of #173

**Closed by RandomFractals** 2021-07-10 12:16 UTC
Labels: duplicate
